theme: jekyll-theme-cayman
#remote_theme: lorepirri/cayman-blog
url: 'https://janshoekstra.github.io'
title: RoboticaWeb
baseurl: "/RoboticaWeb"

defaults:
  - scope:
      path: ""
    values:
      layout: default
