#theme: jekyll-theme-cayman
remote_theme: xukimseven/HardCandy-Jekyll
url: 'https://janshoekstra.github.io'
title: RoboticaWeb
baseurl: "/RoboticaWeb"

#defaults:
  #- scope:
  #    path: *
    #values:
      #theme: jekyll-theme-cayman
      #layout: default
