#theme: jekyll-theme-cayman
#remote_theme: xukimseven/HardCandy-Jekyll
remote_theme: "mmistakes/minimal-mistakes@4.19.2"
url: 'https://janshoekstra.github.io'
title: RoboticaWeb
baseurl: "/RoboticaWeb"

plugins:
  -jekyll-include-cache

#defaults:
  #- scope:
  #    path: *
    #values:
      #theme: jekyll-theme-cayman
      #layout: default
